---
- hosts: wordpress
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: Atualizar pacotes APT
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalar dependências do Apache e PHP
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - libapache2-mod-php
          - unzip
          - git
        state: present

    - name: Remover conteúdo padrão do Apache
      file:
        path: /var/www/html
        state: absent

    - name: Criar diretório /var/www/html
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Clonar repositório para pasta temporária
      git:
        repo: "{{ wordpress_repo }}"
        dest: /tmp/proj
        force: yes

    - name: Copiar conteúdo da pasta /app para o Apache root
      synchronize:
        src: /tmp/proj/app/
        dest: /var/www/html/
        delete: yes
        recursive: yes
        
    - name: Ajustar permissões da pasta /var/www/html
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes

    - name: Reiniciar o Apache
      service:
        name: apache2
        state: restarted
