name: Deploy para EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      if: true
      uses: actions/checkout@v3

    - name: Compactar o projeto
      if: true
      run: |
        tar -czf projeto.tar.gz -C app .

    - name: Copiar o arquivo para a máquina EC2
      if: true
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "projeto.tar.gz"
        target: "~"

    - name: Executar comandos remotos na EC2
      if: true
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Parando Servidor"
          sudo systemctl stop apache2

          echo "Criando backup (sobrescrevendo backup_ultimo.tar.gz)"
          sudo tar -czf ~/backup_ultimo.tar.gz /var/www/html

          echo "Removendo projeto antigo (backup opcional pode ser feito)"
          sudo rm -rf /var/www/html/*

          echo "Descompactando novo projeto"
          sudo tar -xzf projeto.tar.gz -C /var/www/html

          echo "Corrigindo permissões"
          sudo chown -R www-data:www-data /var/www/html
          sudo chmod -R 755 /var/www/html

          echo "Iniciando Apache"
          sudo systemctl start apache2

    - name: Verificação de health-check
      if: true
      id: healthcheck
      continue-on-error: true
      run: |
        echo "Verificando aplicação em http://${{ secrets.EC2_HOST }}/"
        sleep 5
        curl -f http://${{ secrets.EC2_HOST }}
    
    - name: Rollback se health-check não foi sucesso
      if: steps.healthcheck.outcome != 'success'
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Rollback iniciado"
          sudo systemctl stop apache2
          sudo rm -rf /var/www/html/*
          sudo tar -xzf ~/backup_ultimo.tar.gz -C /
          sudo chown -R www-data:www-data /var/www/html
          sudo chmod -R 755 /var/www/html
          sudo systemctl start apache2




